---
title: "Group 5 final project"
author: "Arjun, Flynn, Ricardo, Brandon"
date: "3/1/2022"
output: html_document
---


```{r}
getwd()
```

```{r}
library(tidyverse)
library(janitor)
library(here)
library(ggmap)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(dplyr)
library(ggVennDiagram)
library(ggwordcloud)
library(ggthemes)
```

```{r}
ourdata <- readr::read_csv("train.csv")
```
```{r}
ourdata
```







































































































































































































































































































































































































































































































































































































```{r}
cleandata <- clean_names(ourdata) 
cleandata
```

```{r}
disorders_unique <- cleandata %>% 
  count(disorder_subclass) %>%
  arrange(n)
disorders_unique
```
```{r}
disorders_unique %>% 
  ggplot(aes(x = disorder_subclass, y = n , fill = disorder_subclass)) +
  geom_col(color = "black", alpha = 1, na.rm = TRUE) +
  labs(title = "Occurance of Disorders",
       x = "Disorder",
       y = "Number of patients") +
  theme(plot.title = element_text(size = rel(2), hjust = 0.5)) +
  coord_flip()
```

```{r}
disorders_unique %>% 
ggplot(aes(
  label = disorder_subclass, 
  size = n,
  color = disorder_subclass
  )) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 15) +
  theme_minimal()
```

```{r}
lebers_neuropathy <- cleandata %>%
  filter(disorder_subclass == "Leber's hereditary optic neuropathy") %>%
select(genes_in_mothers_side, inherited_from_father, maternal_gene, paternal_gene)
lebers_neuropathy
```

```{r}
cleandata %>%
  group_by(disorder_subclass) %>%
  summarise(average_bloodcell_count = mean(blood_cell_count_mc_l)) %>%
  arrange(average_bloodcell_count)
```

```{r}
cleandata %>%
   ggplot(aes(x = disorder_subclass, y = blood_cell_count_mc_l, fill= disorder_subclass)) +
  geom_boxplot() +
  labs(title = "blood cell count with disorders",
       x = "Disorder",
       y = "bloodcell count 1000 per microliter")+
  theme(axis.text.x = element_text(angle = 30, hjust=1))
```



```{r}
cleandata %>%
  group_by(disorder_subclass) %>%
  filter(!is.na(white_blood_cell_count_thousand_per_microliter)) %>%
  summarise(average_wbc_count = mean(white_blood_cell_count_thousand_per_microliter)) %>%
  arrange(average_wbc_count)
```

```{r}
cleandata %>%
   ggplot(aes(x = disorder_subclass, y = white_blood_cell_count_thousand_per_microliter, fill = disorder_subclass)) +
  geom_boxplot(color = "black", alpha = 1, na.rm = TRUE) +
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5))+
  theme(axis.text.x = element_text(angle = 30, hjust=1)) +
   labs(title = "WBC count among disorders",
       x = "Disorder",
       y = "WBC count 1000 per microliter")
```

```{r}
cleandata %>%
  select(symptom_1, symptom_2, symptom_3, symptom_4, symptom_5)# %>%
 # summarise(mean (symptom_1, symptom_2, symptom_3, symptom_4, symptom_5))
```

```{r}
cleandata %>%
  filter(!is.na)
  group_by(disorder_subclass) %>%
  summarise(mean(symptom_1)) 
```




















\




































































































































































































































































































